### ISSUE TITLE
Setup effects on wled component

### ISSUE THREAD

**Issue by arivelli** [ayufan/esphome-components#11]
Hey @ayufan, great job, I'm really new on esphome and was really nice to see wled available as a custom component, thanks for your effort.
So, I was able to installed succesfully but I can't see any effect, can you give me a clue of how to put all of them available?

**Comment by ayufan** [comment]
It is now part of `esphome-dev`: https://github.com/esphome/esphome-docs/blob/next/components/light/index.rst#wled. This very well describes that.
