### ISSUE TITLE
EQ3 features

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [ayufan/esphome-components#12]
is it possible to control the EQ3 thermostats with this component or is it just a read only connection to home assistant?
Would be cool if you could update the Readme with this, thanks!

**Comment by aqualx** [comment]
You can control as well.
![image](https://user-images.githubusercontent.com/45320692/86755322-39ea7100-c04a-11ea-81c7-3cb18a96494f.png)
![image](https://user-images.githubusercontent.com/45320692/86755488-5a1a3000-c04a-11ea-9dc8-afb87363ce73.png)

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thx!
