### ISSUE TITLE
e131 Component Only Works on Strips

### ISSUE THREAD

**Issue by rpulivella** [ayufan/esphome-components#14]
Been testing the e131 component in esphome for a few days. This is excellent thanks for the great work!

Now I am trying to use it to drive a single dimmer (Martin Jerry MJ-SD01). I get an error when trying to build that complains:

```
Failed config

light.monochromatic: [source mj_sd02_testing.yaml:84]
  platform: monochromatic
  name: Martin Jerry MJ-SD01
  output: pwm
  default_transition_length: 0s
  id: dimmer
  effects:  [source mj_sd02_testing.yaml:91]
    
    The effect 'e131' is not allowed for this light type.
    - [source mj_sd02_testing.yaml:91]
      e131: 
        universe: 1
        channels: MONO
```

I suspect support would have to be added for this or perhaps I am applying the effect to the wrong component? Or I need a lambda effect in between?

Also would love to see a few inputs added to the web controls to support setting a base DMX address and universe instead of it being hard coded into the yaml.

Thanks!

**Comment by ayufan** [comment]
The `AddressableRGB` strip is required by the component.

**Comment by Kosh42** [comment]
I'd also love to use this, but this time on a ```
light:
- platform: rgbww
```
light. But I get the same not allowed. Trying to keep this light in ESPHome instead of the WLED analogue version (it does exist, but it sucks, unlike the awesome addressable LED version).

**Comment by jdubz666** [comment]
Hey agreed here! I would also love to see this available on RGBWW platform so I can get my light bulbs dancing.

**Comment by ayufan** [comment]
The `e131` is upstreamed. So, additional feature requests should be posted there and maybe someone will pick it.

**Comment by Drun555** [comment]
Yes, E131 opens up so much possibilities (OpenRGB, for example). We definitely need it for bulbs aswell.

**Comment by Jorick-tv** [comment]
Still want this feature. (or better yet; bugfix) 4 years later.

I just spent time soldering and coding just to be greeted with this error message:
`The effect 'e131' is not allowed for this light type.`

**Comment by SparkyDan555** [comment]
You an achieve this by "proxying" the internal light component via a partition light as a workaround.
