### ISSUE TITLE
esp32_ble-clients

### ISSUE THREAD

**Issue by WNTLtd** [ayufan/esphome-components#18]
Could you please expand on how to install/use the esp32_ble_clients.

You have a line in your readme.md saying:
This uses custom esp32_ble_clients implementation to support Bluetooth on ESP32.

But I'm not entirely sure how you go about using this custom implementation.
Is copying the files to the esp/home/custom_components dir enough?
Do I need to put esp32_ble_clients: into my esphome node.yaml file like I would have with esp_ble_tracker:?

Help.....

**Comment by ayufan** [comment]
This is only meant to be used by `eq3_v2`.
