### ISSUE TITLE
frame rate at full res

### ISSUE THREAD

**Issue by timelyfiasco** [ayufan/esphome-components#20]
Hi, I tried this in vlc and a couple hours in zoneminder and it works! Using ESPcam may be a viable alternative for me to network CCTV, especially now that prices for such devices are rising due to IC shortage? While ESP only costs $5.

Question, what determines the frame rate of the stream? On boot I get 4fps but a few seconds after it settles to 1fps - 2fps.

**Comment by ayufan** [comment]
@timelyfiasco 

It depends on amount of customers as this is affected by: if home assistant connected to API: each fetched image will pushed via API effectively reducing rate to half (try to disable API temporarily).

This is something that could be improved.

**Comment by timelyfiasco** [comment]
I dont know how to disable the api. When I uncomment the `api:` the ff appears,
`Component esp32_camera requires component api.`
I removed the integration from hass and the fps starts at 6fps. Then averages to 3fps. Once, it averaged at 4fps. 
This meets my needs. Thanks @ayufan

Is there a possibility of having multiple streaming and H.265 Video compression if the code develops further or is it too much to ask from esp32?

**Comment by ayufan** [comment]
> Is there a possibility of having multiple streaming and H.265 Video compression if the code develops further or is it too much to ask from esp32?

No. The camera outputs jpg, the esp32 just forwards that over WiFi. There is no additional image sygnal processor or video processing unit to do any transformation.

**Comment by timelyfiasco** [comment]
@ayufan thank you for the addon
