### ISSUE TITLE
"custom_components" folder is ignored

### ISSUE THREAD

**Issue by goose2600** [ayufan/esphome-components#3]
Thanks for your work, it's just what I am looking for. 

I followed your instructions but (probably it's a my mistake) compiling inside the Hass.io ESPHome plugin, looks like the "custom_componets" folder is ignored.

Infact, adding platform eq3_v2 in climate.yaml I get this error: "Platform error climate.eq3_v2 - Integration 'eq3_v2' not found".

Home Assistant 0.103.5
ESPhome 1.15.0-dev

EDIT 08/01/2020:
I managed to include the custom component files by editing the device yaml in EspHome:

`includes:`
`  - custom_components/eq3_v2/eq3_const.h`
`  - custom_components/eq3_v2/eq3.h`
`  - custom_components/esp32_ble_clients/esp32_ble_lock.h`
`  - custom_components/esp32_ble_clients/esp32_ble_log.h`
`  - custom_components/esp32_ble_clients/esp32_ble.h`
`  - custom_components/esp32_ble_clients/esp32_ble_client.h`

Anyway, somenthing does not work when compiling: the compiler cannot found the esphome components "sensor.h" and "climate.h (included in eq3.h).

**Comment by vandecook** [comment]
bump this topic. Would be great To get this component work. 
Thanks
Roland

**Comment by ayufan** [comment]
It does work...

**Comment by JamesT42** [comment]
I had to put the custom_components folder inside the esphome folder under hass.io
