### ISSUE TITLE
esphome yaml for inode component has errors

### ISSUE THREAD

**Issue by KM192** [ayufan/esphome-components#4]
Hi,

I was looking for such possibility - integration with iNode energy via esp32.
After coping iNode files into /conf/custom_components/inode_ble/ directory, when edditing esphome yaml file for my esp32 there is an error: 

"Platform not found: sensor.inode_ble"

It seems that I am missing registration somewhere of this custom component implementation.

**Comment by KM192** [comment]
I got it:
- inode_ble directory goes under esphome/custom_components/ 
- you adding include under esphome keyword in yaml

esphome:
  includes:
    - custom_components/inode_ble/inode_ble.h

Time to test.

**Comment by ayufan** [comment]
Include is not needed
