### ISSUE TITLE
eq3_v2: clock source invalid

### ISSUE THREAD

**Issue by disrupted** [ayufan/esphome-components#9]
since I re-flashed my ESP I can't connect to the eQ3 Thermostat anymore. Getting clock source invalid:

```
[18:04:03][I][eq3:052]: Requesting update of <ADDRESS>...
[18:04:07][E][eq3_cmd:144]: Clock source for <ADDRESS> is not valid.
[18:04:07][W][eq3:066]: Update of <ADDRESS> failed. Too many tries.
```

I made sure the time is set correctly on the Thermostat, tried both disabling and enabling dst (summertime) setting and even did a full reset of the device.

**Comment by ayufan** [comment]
ESP32 needs to have time source. Likely sntp from internet.

**Comment by disrupted** [comment]
I already had

```
time:
  - platform: sntp
    id: sntp_time
```

defined in my config. changed that to

```
time:
  - platform: homeassistant
    id: homeassistant_time
```

and now it's working thanks to the sync with Home Assistant. not sure what was wrong with sntp previously though
